version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Asia/Shanghai"
      time: "06:00"
    pull-request-branch-name:
      separator: "-"
